<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit14ff1ae97d63ea29fa4807c79e59db1f
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\Semver\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\Semver\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/semver/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit14ff1ae97d63ea29fa4807c79e59db1f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit14ff1ae97d63ea29fa4807c79e59db1f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit14ff1ae97d63ea29fa4807c79e59db1f::$classMap;

        }, null, ClassLoader::class);
    }
}
